INSERT INTO ekipa (ime, stadion, mesto) VALUES ('Puce', 'Wunsch Group', 'Xujiaqiao') 
INSERT INTO ekipa (ime, stadion, mesto) VALUES ('Fuscia', ' Hane Paucek and Simonis', 'Union') 
INSERT INTO ekipa (ime, stadion, mesto) VALUES ('Blue', 'Becker-Hudson', 'Konsoy') 
INSERT INTO ekipa (ime, stadion, mesto) VALUES ('Maroon', 'Jast and Sons', 'Haapajärvi') 
INSERT INTO ekipa (ime, stadion, mesto) VALUES ('Orange', 'Howell-Crooks', 'Baki') 
INSERT INTO ekipa (ime, stadion, mesto) VALUES ('Crimson', 'Koelpin-Osinski', 'Krajan') 
INSERT INTO ekipa (ime, stadion, mesto) VALUES ('Mauv', 'Raynor-Zieme', 'Coronel Belisle') 
INSERT INTO ekipa (ime, stadion, mesto) VALUES ('Aquamarine', 'Parker-Wunsch', 'Palmeira') 
INSERT INTO ekipa (ime, stadion, mesto) VALUES ('Violet', 'Nienow LLC', 'Bang Phlat') 
INSERT INTO ekipa (ime, stadion, mesto) VALUES ('Indigo', ' Ullrich Jacobson Kozey', 'Tuymazy') 
